*Практические* задания к уроку №2

###Вычисления с помощью Numpy







Задание 1

Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием “а” размером 5x2, 
то есть состоящий из 5 строк и 2 столбцов. 
Первый столбец должен содержать числа 1, 2, 3, 3, 1, 
а второй - числа 6, 8, 11, 10, 7. 
Будем считать, что каждый столбец - это признак, а строка - наблюдение. 
Затем найдите среднее значение по каждому признаку, 
используя метод mean массива Numpy. 
Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [ ]:
import numpy as np

a = np.array([[1, 6],
[2, 8],
[3, 11],
[3, 10],
[1, 7]])

print(a)
mean_a = a.mean(axis=0)
print("Средние значения столбцов: {}".format(mean_a))

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]
Средние значения столбцов: [2.  8.4]


Задание 2

Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, 
содержащиеся в массиве mean_a. 
Вычисление должно производиться в одно действие. 
Получившийся массив должен иметь размер 5x2.


In [ ]:
a_centered = a - mean_a
print (a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


Задание 3

Найдите скалярное произведение столбцов массива a_centered. 
 результате должна получиться величина a_centered_sp. 
 Затем поделите a_centered_sp на N-1, где N - число наблюдений.


In [ ]:
b = a_centered[:5, 0]

c = a_centered[:5, 1]

a_centered_sp = np.dot(b,c)
print("Скалярное произведение столбцов: {}".format(a_centered_sp))

num_rows, num_cols = a.shape
print("Количество строк:  ", num_rows)
x = a_centered_sp/(num_rows - 1)

print ("Результат вычислений:  ", x)

Скалярное произведение столбцов: 8.0
Количество строк:   5
Результат вычислений:   2.0


Задание 4**

Число, которое мы получили в конце задания 3 является ковариацией двух признаков, 
содержащихся в массиве “а”. 

В задании 4 мы делили сумму произведений центрированных признаков на N-1, 
а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации.

В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.


In [ ]:
a_t = a.T
print("транспонированная матрица: ")
print(a_t)

x = np.cov(a_t)
print("матрица ковариации: ")
print(x)

транспонированная матрица: 
[[ 1  2  3  3  1]
 [ 6  8 11 10  7]]
матрица ковариации: 
[[1.  2. ]
 [2.  4.3]]


###Тема “Работа с данными в Pandas”

Задание 1


Импортируйте библиотеку Pandas и дайте ей псевдоним pd. 
Создайте датафрейм authors со столбцами author_id и author_name, 
в которых соответственно содержатся данные: 

[1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].

Затем создайте датафрейм book cо столбцами author_id, book_title и price, 
в которых соответственно содержатся данные: 
 
[1, 1, 1, 2, 2, 3, 3],

['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],

[450, 300, 350, 500, 450, 370, 290].


In [ ]:
import pandas as pd

a = {
    "author_id": [1, 2, 3],
    "author_name": ["Тургенев", "Чехов", "Островский"]
}

authors = pd.DataFrame(a)

print (authors)


a = {
    "author_id": [1, 1, 1, 2, 2, 3, 3],
    "book_title": ["Отцы и дети", "Рудин", "Дворянское гнездо", "Толстый и тонкий", "Дама с собачкой", "Гроза", "Таланты и поклонники"],
    "price": ["450", "300", "350", "500", "450", "370", "290"]
}

book = pd.DataFrame(a)

print (book)

   author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский
   author_id            book_title price
0          1           Отцы и дети   450
1          1                 Рудин   300
2          1     Дворянское гнездо   350
3          2      Толстый и тонкий   500
4          2       Дама с собачкой   450
5          3                 Гроза   370
6          3  Таланты и поклонники   290


Задание 2

Получите датафрейм authors_price, 
соединив датафреймы authors и books по полю author_id.


In [ ]:
authors_price = pd.merge(authors, book, on='author_id', how='inner')

print (authors_price)


   author_id author_name            book_title price
0          1    Тургенев           Отцы и дети   450
1          1    Тургенев                 Рудин   300
2          1    Тургенев     Дворянское гнездо   350
3          2       Чехов      Толстый и тонкий   500
4          2       Чехов       Дама с собачкой   450
5          3  Островский                 Гроза   370
6          3  Островский  Таланты и поклонники   290


Задание 3

Создайте датафрейм top5, 
в котором содержатся строки из authors_price с пятью самыми дорогими книгами.


In [ ]:
top5 = authors_price.sort_values(by='price', ascending = False).reset_index(drop=True)

top5 = top5.drop(labels = [5,6],axis = 0)

print(top5)

   author_id author_name         book_title price
0          2       Чехов   Толстый и тонкий   500
1          1    Тургенев        Отцы и дети   450
2          2       Чехов    Дама с собачкой   450
3          3  Островский              Гроза   370
4          1    Тургенев  Дворянское гнездо   350


*Задание* 4

Создайте датафрейм authors_stat на основе информации из authors_price. 

В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price,

в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.


Задание 5**

Создайте новый столбец в датафрейме authors_price под названием cover, 
в нем будут располагаться данные о том, 
какая обложка у данной книги - твердая или мягкая. 

В этот столбец поместите данные из следующего списка:
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].

Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака.
Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. 
Используйте для этого функцию pd.pivot_table. 
При этом столбцы должны называться "твердая" и "мягкая", 
а индексами должны быть фамилии авторов. 
Пропущенные значения стоимостей заполните нулями, 

Назовите полученный датасет book_info и сохраните его в формат pickle 
под названием "book_info.pkl". 
Затем загрузите из этого файла датафрейм и назовите его book_info2. Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.
